### ISSUE TITLE
to-do for next week

### ISSUE THREAD

**Issue by ruzekle** [zleap/torios-manual#12]
This next contribution will be towards the torios-manual. In my next merge I will work on three things:

1) Converting the main .tex into HTML.
2) Modularizing the apps.tex file into several files under desktop folder.
3) Formatting the .tex manual.

---

Week after I intend:

1) Create package for PPA.
2) Make suggested changes to the install-pdftex.sh package.

**Comment by Smile4ever** [comment]
Regarding point 1, is there some sequence to fit the TEX files in each other? Making one TEX file to html is really easy, just use the generatehtml.sh file (adapt the file names where needed).

**Comment by ruzekle** [comment]
Thanks for the information.

I added generatehtml.sh to torios-manual (developmental). First, delete the contents in html folder. I wasn't able to push a commit that would get rid of the content in the html folder.

I will not close this issue since I still have the following to complete:
2) Modularizing the apps.tex file into several files under desktop folder.
3) Formatting the .tex manual.
