### ISSUE TITLE
New Organization of Data

### ISSUE THREAD

**Issue by ruzekle** [zleap/torios-manual#5]
Clean up of old data, removal of irrelevant data, and version control should be done so that there is a testing, stable, and archival versions. Testing will be worked on for the next release while stable is used for the operating system. Archival can be used for saving data like logo and old blog posts.

**Comment by Israel-** [comment]
Hi Sam,
Paul is in the process of redoing the manual, and doing most of what you have said.  He just recently created the first release for this purpose.
I am going to repackage the documentation differently once everything is completed.  We are mainly using html (built from LaTeX) for the end user version.  This way we can include multiple languages and still reuse the same images and the entire documentation will be very small and can (possibly) be included in one package and then we can revise the desktop files to find the system locale and xdg-open the appropriate language, for example using 
xdg-open "${LANG/.*/-}"index.html

**Comment by ruzekle** [comment]
Awesome! Right now there seems to be a lot of files in the repos that don't make much sense to me.

Here's what I'm familiar with: https://code.launchpad.net/ubuntu-manual

Maybe we could structure the repos like this?

**Comment by Israel-** [comment]
You might get a pretty quick response e-mailing the mailing list about your ideas.  I only package the manual, and make the desktop file to open it. :)

**Comment by ruzekle** [comment]
Update: I won't be using the regular Ubuntu manual but take from it as I originally planned.

**Comment by ruzekle** [comment]
submitting pull request
